export plexos_countries

const plexos_countries = [

"Afghanistan" GADM("Afghanistan")
"Albania" GADM("Albania")
"Algeria" GADM("Algeria")
"Angola" GADM("Angola")
"Argentina" GADM("Argentina")
"Armenia" GADM("Armenia")
"Australia" GADM("Australia")
"Austria" GADM("Austria")
"Azerbaijan" GADM("Azerbaijan")

"BHR" GADM("Bahrain")
"BGD" GADM("Bangladesh")
"BLR" GADM("Belarus")
"BEL" GADM("Belgium")
"BEN" GADM("Benin")
"BTN" GADM("Bhutan")
"BOL" GADM("Bolivia")
"BIH" GADM("Bosnia and Herzegovina")
"BWA" GADM("Botswana")
"BRA" GADM("Brazil")
"BRN" GADM("Brunei")
"BGR" GADM("Bulgaria")
"BFA" GADM("Burkina Faso")
"BDI" GADM("Burundi")

"KHM" GADM("Cambodia")
"CMR" GADM("Cameroon")
"CAN" GADM("Canada")
"CPV" GADM("Cape Verde")
"CAF" GADM("Central African Republic")
"TCD" GADM("Chad")
"CHL" GADM("Chile")
"TCD" GADM("Chad")
"CHN" GADM("China")
"COL" GADM("Colombia")
"COD" GADM("Democratic Republic of the Congo")
"CRI" GADM("Costa Rica")
"CIV" GADM("Côte d'Ivoire")
"HRV" GADM("Croatia")
"CUB" GADM("Cuba")
"CYP" GADM("Cyprus")
"CZE" GADM("Czech Republic")

"DNK" GADM("Denmark")
"DJI" GADM("Djibouti")
"DMA" GADM("Dominica")
"DOM" GADM("Dominican Republic")

"ECU" GADM("Ecuador")
"EGY" GADM("Egypt")
"SLV" GADM("El Salvador")
"GNQ" GADM("Equatorial Guinea")
"ERI" GADM("Eritrea")
"EST" GADM("Estonia")
"ETH" GADM("Ethiopia")

"FJI" GADM("Fiji")
"FIN" GADM("Finland")
"FRA" GADM("France")
"GUF" GADM("French Guiana")

"GAB" GADM("Gabon")
"GMB" GADM("Gambia")
"GEO" GADM("Georgia")
"DEU" GADM("Germany")
"GHA" GADM("Ghana")
"GRE" GADM("Greece")
"GTM" GADM("Guatemala")
"GIN" GADM("Guinea")
"GNB" GADM("Guinea-Bissau")
"GUY" GADM("Guyana")

"HND" GADM("Honduras")
"HKG" GADM("Hong Kong")
"HUN" GADM("Hungary")

"ISL" GADM("Iceland")
"IND" GADM("India")
"IDN" GADM("Indonesia")
"IRN" GADM("Iran")
"IRQ" GADM("Iraq")
"IRL" GADM("Ireland")
"IMN" GADM("Isle of Man")
"ISR" GADM("Israel")
"ITA" GADM("Italy")

"JAM" GADM("Jamaica")
"JPN" GADM("Japan")
"JOR" GADM("Jordan")

"KAZ" GADM("Kazakhstan")
"KEN" GADM("Kenya")
"XKO" GADM("Kosovo")
"KWT" GADM("Kuwait")
"KGZ" GADM("Kyrgyzstan")

"LAO" GADM("Laos")
"LVA" GADM("Latvia")
"LBN" GADM("Lebanon")
"LSO" GADM("Lesotho")
"LBR" GADM("Liberia")
"LBY" GADM("Libya")
"LIE" GADM("Liechtenstein")
"LTU" GADM("Lithuania")
"LUX" GADM("Luxembourg")


"MKD" GADM("Macedonia")
"MDG" GADM("Madagascar")
"MWI" GADM("Malawi")
"MYS" GADM("Malaysia")
"MDV" GADM("Maldives")
"MLI" GADM("Mali")
"MLT" GADM("Malta")
"MRT" GADM("Mauritania")
"MEX" GADM("Mexico")
"MDA" GADM("Moldova")
"MCO" GADM("Monaco")
"MNG" GADM("Mongolia")
"MNE" GADM("Montenegro")
"MAR" GADM("Morocco")
"MOZ" GADM("Mozambique")
"MMR" GADM("Myanmar")

"NAM" GADM("Namibia")

"NPL" GADM("Nepal")
"NLD" GADM("Netherlands")

"NZL" GADM("New Zealand")
"NIC" GADM("Nicaragua")
"NER" GADM("Niger")
"NGA" GADM("Nigeria")
"PRK" GADM("North Korea")
"XNC" GADM("Northern Cyprus")
"NOR" GADM("Norway")

"OMN" GADM("Oman")

"PAK" GADM("Pakistan")

"PSE" GADM("Palestina")
"PAN" GADM("Panama")
"PNG" GADM("Papua New Guinea")
"PRY" GADM("Paraguay")
"PER" GADM("Peru")
"PHL" GADM("Philippines")
"POL" GADM("Poland")
"PRT" GADM("Portugal")
"PRI" GADM("Puerto Rico")

"QAT" GADM("Qatar")

"COG" GADM("Republic of Congo")
"ROU" GADM("Romania")
"RUS" GADM("Russia")
"RWA" GADM("Rwanda")

"SAU" GADM("Saudi Arabia")
"SEN" GADM("Senegal")
"SRB" GADM("Serbia")
"SLE" GADM("Sierra Leone")
"SGP" GADM("Singapore")
"SVK" GADM("Slovakia")
"SVN" GADM("Slovenia")
"SOM" GADM("Somalia")
"ZAF" GADM("South Africa")
"KOR" GADM("South Korea")
"SSD" GADM("South Sudan")
"ESP" GADM("Spain")
"LKA" GADM("Sri Lanka")
"SDN" GADM("Sudan")
"SUR" GADM("Suriname")
"SWZ" GADM("Swaziland")
"SWE" GADM("Sweden")
"CHE" GADM("Switzerland")
"SYR" GADM("Syria")

"TWN" GADM("Taiwan")
"TJK" GADM("Tajikistan")
"TZA" GADM("Tanzania")
"THA" GADM("Thailand")
"TLS" GADM("East Timor")
"TGO" GADM("Togo")
"TKL" GADM("Tokelau")
"TON" GADM("Tonga")
"TTO" GADM("Trinidad and Tobago")
"TUN" GADM("Tunisia")
"TUR" GADM("Turkey")
"TKM" GADM("Turkmenistan")

"UGA" GADM("Uganda")
"UKR" GADM("Ukraine")
"ARE" GADM("United Arab Emirates")
"GBR" GADM("United Kingdom")
"USA" GADM("United States")
"UMI" GADM("United States Minor Outlying Islands")
"URY" GADM("Uruguay")
"UZB" GADM("Uzbekistan")

"VUT" GADM("Vanuatu")
"VEN" GADM("Venezuela")
"VNM" GADM("Vietnam")

"ESH" GADM("Western Sahara")

"YEM" GADM("Yemen")

"ZMB" GADM("Zambia")
"ZWE" GADM("Zimbabwe")
]
