export Acountries, Bcountries, Ccountries, Dcountries, Ecountries
        , Fcountries, Gcountries, Hcountries, Icountries, Jcountries
        , Kcountries, Lcountries, Mcountries, Ncountries, Ocountries
        , Pcountries, Qcountries, Rcountries, Scountries, Tcountries
        , Ucountries, Vcountries, Wcountries, #=Xcountries=#, Ycountries
        , Zcountries


const Acountries = [
"AFG" GADM("Afghanistan")
"XAD" GADM("Akrotiri and Dhekelia")
"ALA" GADM("Åland")
"ALB" GADM("Albania")
"DZA" GADM("Algeria")
"ASM" GADM("American Samoa")
"AND" GADM("Andorra")
"AGO" GADM("Angola")
"AIA" GADM("Anguilla")
"ATG" GADM("Antigua and Barbuda")
"ARG" GADM("Argentina")
"ARM" GADM("Armenia")
"ABW" GADM("Aruba")
"AUS" GADM("Australia")
"AUT" GADM("Austria")
"AZE" GADM("Azerbaijan")
]
const Bcountries = [
"BHS" GADM("Bahamas")
"BHR" GADM("Bahrain")
"BGD" GADM("Bangladesh")
"BRB" GADM("Barbados")
"BLR" GADM("Belarus")
"BEL" GADM("Belgium")
"BLZ" GADM("Belize")
"BEN" GADM("Benin")
"BMU" GADM("Bermuda")
"BTN" GADM("Bhutan")
"BOL" GADM("Bolivia")
"BIH" GADM("Bosnia and Herzegovina")
"BWA" GADM("Botswana")
"BVT" GADM("Bouvet Island")
"BRA" GADM("Brazil")
"IOT" GADM("British Indian Ocean Territory")
"VGB" GADM("British Virgin Islands")
"BRN" GADM("Brunei")
"BGR" GADM("Bulgaria")
"BFA" GADM("Burkina Faso")
"BDI" GADM("Burundi")
]
const Ccountries = [
"KHM" GADM("Cambodia")
"CMR" GADM("Cameroon")
"CAN" GADM("Canada")
"CPV" GADM("Cape Verde")
#"XCA" GADM("Caspian Sea")
"CYM" GADM("Cayman Islands")
"CAF" GADM("Central African Republic")
"TCD" GADM("Chad")
"CHL" GADM("Chile")
"TCD" GADM("Chad")
"CHN" GADM("China")
"CXR" GADM("Christmas Island")
"XCL" GADM("Clipperton Island")
"CCK" GADM("Cocos Islands")
"COL" GADM("Colombia")
"COM" GADM("Comoros")
"COK" GADM("Cook Islands")
"CRI" GADM("Costa Rica")
"CIV" GADM("Côte d'Ivoire")
"HRV" GADM("Croatia")
"CUB" GADM("Cuba")
"CUW" GADM("Curaçao")
"CYP" GADM("Cyprus")
"CZE" GADM("Czech Republic")
]
const Dcountries = [
"COD" GADM("Democratic Republic of the Congo")
"DNK" GADM("Denmark")
"DJI" GADM("Djibouti")
"DMA" GADM("Dominica")
"DOM" GADM("Dominican Republic")
"DMA" GADM("Dominica")
]
const Ecountries = [
"ECU" GADM("Ecuador")
"EGY" GADM("Egypt")
"SLV" GADM("El Salvador")
"GNQ" GADM("Equatorial Guinea")
"ERI" GADM("Eritrea")
"EST" GADM("Estonia")
"ETH" GADM("Ethiopia")
]
const Fcountries = [
"FLK" GADM("Falkland Islands")
"FRO" GADM("Faroe Islands")
"FJI" GADM("Fiji")
"FIN" GADM("Finland")
"FRA" GADM("France")
"GUF" GADM("French Guiana")
"PYF" GADM("French Polynesia")
#"ATF" GADM("French Southern Territories")
]
const Gcountries =[
"GAB" GADM("Gabon")
"GMB" GADM("Gambia")
"GEO" GADM("Georgia")
"DEU" GADM("Germany")
"GHA" GADM("Ghana")
"GIB" GADM("Gibraltar")
"GRE" GADM("Greece")
"GRL" GADM("Greenland")
"GRD" GADM("Grenada")
"GLP" GADM("Guadeloupe")
"GUM" GADM("Guam")
"GTM" GADM("Guatemala")
"GGY" GADM("Guernsey")
"GIN" GADM("Guinea")
"GNB" GADM("Guinea-Bissau")
"GUY" GADM("Guyana")
]
const Hcountries =[
"HTI" GADM("Haiti")
"HMD" GADM("Heard Island and McDonald Islands")
"HND" GADM("Honduras")
"HKG" GADM("Hong Kong")
"HUN" GADM("Hungary")
"HND" GADM("Honduras")
]
const Icountries =[
"ISL" GADM("Iceland")
"IND" GADM("India")
"IDN" GADM("Indonesia")
"IRN" GADM("Iran")
"IRQ" GADM("Iraq")
"IRL" GADM("Ireland")
"IMN" GADM("Isle of Man")
"ISR" GADM("Israel")
"ITA" GADM("Italy")
]
const Jcountries =[
"JAM" GADM("Jamaica")
"JPN" GADM("Japan")
"JEY" GADM("Jersey")
"JOR" GADM("Jordan")
]
const Kcountries =[
"KAZ" GADM("Kazakhstan")
"KEN" GADM("Kenya")
"KIR" GADM("Kiribati")
"XKO" GADM("Kosovo")
"KWT" GADM("Kuwait")
"KGZ" GADM("Kyrgyzstan")
]
const Lcountries =[
"LAO" GADM("Laos")
"LVA" GADM("Latvia")
"LBN" GADM("Lebanon")
"LSO" GADM("Lesotho")
"LBR" GADM("Liberia")
"LBY" GADM("Libya")
"LIE" GADM("Liechtenstein")
"LTU" GADM("Lithuania")
"LUX" GADM("Luxembourg")
]
const Mcountries =[
"MAC" GADM("Macao")
"MKD" GADM("Macedonia")
"MDG" GADM("Madagascar")
"MWI" GADM("Malawi")
"MYS" GADM("Malaysia")
"MDV" GADM("Maldives")
"MLI" GADM("Mali")
"MLT" GADM("Malta")
"MHL" GADM("Marshall Islands")
"MTQ" GADM("Martinique")
"MRT" GADM("Mauritania")
"MUS" GADM("Mauritius")
"MYT" GADM("Mayotte")
"MEX" GADM("Mexico")
"FSM" GADM("Micronesia")
"MDA" GADM("Moldova")
"MCO" GADM("Monaco")
"MNG" GADM("Mongolia")
"MNE" GADM("Montenegro")
"MSR" GADM("Montserrat")
"MAR" GADM("Morocco")
"MOZ" GADM("Mozambique")
"MMR" GADM("Myanmar")
]
const Ncountries =[
"NAM" GADM("Namibia")
"NRU" GADM("Nauru")
"NPL" GADM("Nepal")
"NLD" GADM("Netherlands")
"NCL" GADM("New Caledonia")
"NZL" GADM("New Zealand")
"NIC" GADM("Nicaragua")
"NER" GADM("Niger")
"NGA" GADM("Nigeria")
"NIU" GADM("Niue")
"NFK" GADM("Norfolk Island")
"PRK" GADM("North Korea")
"XNC" GADM("Northern Cyprus")
"MNP" GADM("Northern Mariana Islands")
"NOR" GADM("Norway")
]
const Ocountries =[
"OMN" GADM("Oman")
]
const Pcountries =[
"PAK" GADM("Pakistan")
"PLW" GADM("Palau")
"PSE" GADM("Palestina")
"PAN" GADM("Panama")
"PNG" GADM("Papua New Guinea")
"PRY" GADM("Paraguay")
"PER" GADM("Peru")
"PHL" GADM("Philippines")
"PCN" GADM("Pitcairn Islands")
"POL" GADM("Poland")
"PRT" GADM("Portugal")
"PRI" GADM("Puerto Rico")
]
const Qcountries =[
"QAT" GADM("Qatar")
]
const Rcountries =[
"COG" GADM("Republic of Congo")
"REU" GADM("Reunion")
"ROU" GADM("Romania")
"RUS" GADM("Russia")
"RWA" GADM("Rwanda")
]
const Scountries =[
"BLM" GADM("Saint-Barthélemy")
"MAF" GADM("Saint-Martin")
"MHN" GADM("Saint Helena")
"KNA" GADM("Saint Kitts and Nevis")
"LCA" GADM("Saint Lucia")
"SPM" GADM("Saint Pierre and Miquelon")
"VCT" GADM("Saint Vincent and the Grenadines")
"WSM" GADM("Samoa")
"SMR" GADM("San Marino")
"STP" GADM("Sao Tome and Principe")
"SAU" GADM("Saudi Arabia")
"SEN" GADM("Senegal")
"SRB" GADM("Serbia")
"SYC" GADM("Seychelles")
"SLE" GADM("Sierra Leone")
"SGP" GADM("Singapore")
"SVK" GADM("Slovakia")
"SVN" GADM("Slovenia")
"SLB" GADM("Solomon Islands")
"SOM" GADM("Somalia")
"ZAF" GADM("South Africa")
"SGS" GADM("South Georgia and the South Sandwich Islands")
"KOR" GADM("South Korea")
"SSD" GADM("South Sudan")
"ESP" GADM("Spain")
"LKA" GADM("Sri Lanka")
"SDN" GADM("Sudan")
"SUR" GADM("Suriname")
"SJM" GADM("Svalbard and Jan Mayen")
"SWZ" GADM("Swaziland")
"SWE" GADM("Sweden")
"CHE" GADM("Switzerland")
"SYR" GADM("Syria")
]
const Tcountries =[
"TWN" GADM("Taiwan")
"TJK" GADM("Tajikistan")
"TZA" GADM("Tanzania")
"THA" GADM("Thailand")
"TLS" GADM("East Timor")
"TGO" GADM("Togo")
"TKL" GADM("Tokelau")
"TON" GADM("Tonga")
"TTO" GADM("Trinidad and Tobago")
"TUN" GADM("Tunisia")
"TUR" GADM("Turkey")
"TKM" GADM("Turkmenistan")
"TCA" GADM("Turks and Caicos Islands")
"TUV" GADM("Tuvalu")
]
const Ucountries =[
"UGA" GADM("Uganda")
"UKR" GADM("Ukraine")
"ARE" GADM("United Arab Emirates")
"GBR" GADM("United Kingdom")
"USA" GADM("United States")
"UMI" GADM("United States Minor Outlying Islands")
"URY" GADM("Uruguay")
"UZB" GADM("Uzbekistan")
]
const Vcountries =[
"VUT" GADM("Vanuatu")
"VAT" GADM("Vatican City")
"VEN" GADM("Venezuela")
"VNM" GADM("Vietnam")
"VIR" GADM("Virgin Islands, U.S.")
]
const Wcountries =[
"WLF" GADM("Wallis and Futuna")
"ESH" GADM("Western Sahara")
]
const Ycountries =[
"YEM" GADM("Yemen")
]
const Zcountries =[
"ZMB" GADM("Zambia")
"ZWE" GADM("Zimbabwe")
]
